#!/usr/bin/env python3
"""
DEMO: Content Variety Showcase
Shows 10 random posts generated by the Dynamic Viral Engine
Run this to see the variety and quality of generated content
"""

import sys
sys.path.insert(0, '/root/webapp')

from dynamic_viral_engine import ViralContentGenerator

def main():
    print("=" * 80)
    print("🎨 DYNAMIC VIRAL CONTENT ENGINE - VARIETY SHOWCASE")
    print("=" * 80)
    print("\nGenerating 10 random posts to demonstrate variety...\n")
    
    # Initialize generator with your token info
    generator = ViralContentGenerator(
        ticker="$AIINU",
        contract="0x313B7696a8566Ce850c865Dc60b7676F1e797B07",
        dex_link="https://www.clanker.world/clanker/0x313B7696a8566Ce850c865Dc60b7676F1e797B07"
    )
    
    # Generate 10 posts
    for i in range(10):
        print(f"\n{'─' * 80}")
        print(f"📄 POST #{i+1}")
        print('─' * 80)
        
        # 75% chance for full post, 25% for short
        import random
        if random.random() < 0.25:
            title, content = generator.generate_short_post()
            print(f"Format: SHORT")
        else:
            title, content = generator.generate_post()
            print(f"Format: FULL")
        
        print(f"\nTitle: {title}")
        print(f"\nContent:\n{content}")
    
    print("\n" + "=" * 80)
    print("✅ Demo Complete!")
    print("=" * 80)
    print("\n💡 Key Takeaways:")
    print("   • Every post is unique and human-like")
    print("   • Different angles: FOMO, Technical, Community, Meme, Professional")
    print("   • 168,760+ possible combinations")
    print("   • No external APIs needed")
    print("   • Ready to run 24/7 without repetition")
    print("\n🚀 Ready to deploy? Run: python3 dynamic_viral_engine.py")
    print("=" * 80 + "\n")

if __name__ == "__main__":
    main()
